import { create } from "zustand";
export const useLargeTextStore = create((set) => ({
    fileInfo: null,
    visibleLines: [],
    searchQuery: "",
    searchType: "visible",
    searchResults: [],
    totalMatches: 0,
    currentLine: 0,
    caseSensitive: false,
    useRegex: false,
    loading: false,
    showFindDialog: false,
    showReplaceDialog: false,
    showGotoDialog: false,
    isLoadingLines: false,
    setFileInfo: (fileInfo) => set({ fileInfo }),
    setVisibleLines: (lines) => set({ visibleLines: lines }),
    setSearchQuery: (query) => set({ searchQuery: query }),
    setSearchType: (type) => set({ searchType: type }),
    setSearchResults: (results) => set({ searchResults: results }),
    setTotalMatches: (total) => set({ totalMatches: total }),
    setCurrentLine: (line) => set({ currentLine: line }),
    setCaseSensitive: (value) => set({ caseSensitive: value }),
    setUseRegex: (value) => set({ useRegex: value }),
    setLoading: (value) => set({ loading: value }),
    setShowFindDialog: (value) => set({ showFindDialog: value }),
    setShowReplaceDialog: (value) => set({ showReplaceDialog: value }),
    setShowGotoDialog: (value) => set({ showGotoDialog: value }),
    setIsLoadingLines: (value) => set({ isLoadingLines: value }),
    clearSearch: () => set({
        searchQuery: "",
        searchResults: [],
        totalMatches: 0,
    }),
    cleanup: () => set({
        fileInfo: null,
        visibleLines: [],
        searchQuery: "",
        searchResults: [],
        totalMatches: 0,
        currentLine: 0,
    }),
}));
//# sourceMappingURL=largeTextStore.js.map